name: '💡 Feature Request'
description: Ideas for other new features or improvements
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: '💡 Description'
      description: A clear and concise description of the new feature..
    validations:
      required: true